const planets=[
  {
    planetRadius:1,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:1,
    speed:0.005,
    orbitalRadius:20,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.001,
    elevation:0
  },
  {
    planetRadius:1.5,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:2,
    speed:0.001,
    orbitalRadius:50,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.02,
    elevation:0
  },
  {
    planetRadius:2,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:3,
    speed:0.0001,
    orbitalRadius:70,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.03,
    elevation:0
  },
  {
    planetRadius:2,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:4,
    speed:0.0001,
    orbitalRadius:110,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.01,
    elevation:0
  },
  //+1
  {
    planetRadius:1,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:5,
    speed:0.003,
    orbitalRadius:20,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.02,
    elevation:5
  },
  {
    planetRadius:1.5,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:6,
    speed:0.0025,
    orbitalRadius:50,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.03,
    elevation:10
  },
  {
    planetRadius:2,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:1,
    speed:0.002,
    orbitalRadius:70,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.03,
    elevation:15
  },
  {
    planetRadius:4,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:3,
    speed:0.001,
    orbitalRadius:90,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.02,
    elevation:20
  },
  //+2
  {
    planetRadius:1.5,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:5,
    speed:0.0026,
    orbitalRadius:30,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.03,
    elevation:30
  },
  {
    planetRadius:2,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:2,
    speed:0.001,
    orbitalRadius:60,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.02,
    elevation:40
  },
  //+3
  {
    planetRadius:0.5,
    planetHeight:64,
    planetWidth:64,
    planetTexture:"./planetTexture.png",
    startingRadian:5,
    speed:0.004,
    orbitalRadius:20,
    orbiatalCenter:{
      x:0,
      z:0
    },
    rotationSpeed:0.01,
    elevation:50
  }
]

export default planets